accessing
exception: anObject
	"Set the value of exception"

	exception := anObject